language: node_js
node_js:
  - "8.11"
script: 
  - npm run demo
deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master